spring:
  thymeleaf:
    enabled: true
  mail:
    from: marshmallow_1@bk.ru
    host: smtp.mail.ru
    port: 465
    username: marshmallow_1@bk.ru
    password:
    smtps:
      auth: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtps
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/marshmallows
    username: marshmallows
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 256
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
authorization:
  verification-code-ttl: 10
  signing:
    key: fojsgdfuihdfogudfhdfguoidfilufjndoffnjknmkjlf
#logging:
#  level:
#    org.springframework.security: debug